name: 'ab_testing_pipeline'
version: '1.0.0'
config-version: 2

profile: 'ab_testing_pipeline'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ab_testing_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table